---
default_language_version:
  python: python3

repos:
  # This is for maintaining consistency of the GitHUB Action Worfklow files
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    name: YAML-format
    args:
    - '--mapping=2'
    - '--sequence=2'
    - '--offset=0'
    - '--width=120'
    - '--preserve-quotes'
    types: [file]
    files: \.(yaml|yml|config|workflow)$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    name: Python-lint-ruff
    args: [--fix]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.12.0
  hooks:
  - id: mypy
    name: Python-lint-mypy
    exclude: docs/source/conf.py
