---
name: Deploy Docs to gh-pages

on:
  push:
    branches:
    - main
    tags:
    - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Documentation
      run: make build install docs-build

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Update versions.json
      run: |
        mkdir -p gh-pages/en
        ./.makeflow/docs_versions.py --docs docs/build/html --site gh-pages --ref "${{ github.ref }}"

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd gh-pages
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add site
        touch .nojekyll
        git add .nojekyll
        git commit -m "Update documentation from ${{ github.sha }}" || echo "No changes to commit"
        git push origin gh-pages
